### PR TITLE
Nested derived type bug fix

### PR DESCRIPTION
**Pull request by rolfhm**
Possibly a solution to issue https://github.com/ecmwf-ifs/loki/issues/182

### CODE REVIEW

**Comment by mlange05** [comment]
Hi @rolfhm I just found this, and have recently stumbled across a slightly better fix. I really like your test though, so I've just triggered a rebase, and will bring this in with the other fix on top, I think. Hope you don't mind?

**Comment by rolfhm** [comment]
No problem. Glad it was of some use.
Just noticed there's a double 'replace' in the test docstring

**Review by mlange05 — APPROVED** [review]
Apologies for the delay in picking this up. The test is neat and the problem had been fixed in another branch already. I've brought this all up to speed with latest main and consolidated (probably should be a squash-merge). GTG from me.

**Review by reuterbal — APPROVED** [review]
Thanks all, fix looks great and test is much appreciated. GTG!

**Pull request merged**
