### PR TITLE
F2C: optional case-sensitivity for variables/symbols

### PR DESCRIPTION
**Pull request by MichaelSt98**
`convert_to_lower_case()` if not variable/symbol `.case_sensitive=True`

Imported for things like: 

```c
... = threadIdx.x
cudaMalloc(...)
```

### CODE REVIEW

**Review by reuterbal — CHANGES_REQUESTED** [review]
Thanks. That's a good solution to the specific problem. 

I think `MetaSymbol` should derive the `case_sensitive` value directly from the wrapped `symbol`. Otherwise this looks good to me.

**Review by reuterbal — APPROVED** [review]
Thanks, looks good to me now!

**Comment by reuterbal** [comment]
There seems some test failures after the latest rebase - hold off on merging until this is fixed.

**Review by mlange05 — APPROVED** [review]
Yes, makes sense and looks good. GTG from me. :shipit:

**Pull request merged**
