### PR TITLE
Add support of the FORALL statement and construct (fparser/fgen)

### PR DESCRIPTION
**Pull request by quepas**
This pull request adds support of the FORALL statement and construct: [Intel Developer Reference - FORALL](https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2024-0/forall.html). Adding the FORALL support has been mentioned in #117.

I tried to mimic your coding style as much as possible. I am looking forward to your review!

### CODE REVIEW

**Review by reuterbal — CHANGES_REQUESTED** [review]
Thank you, this is a valuable addition, neatly implemented and documented! We really appreciate it.

Before we can integrate this, I'll have to ask for two additions:

1) We need some tests for the new IR node. I think [`test_control_flow.py`](https://github.com/ecmwf-ifs/loki/blob/main/tests/test_control_flow.py) would be a good place for this. Take a look at the other tests for inspiration, but in essence: Write some Fortran routine that contains Forall and uses it in the variety of flavours that are implemented. Then parse the code and inspect the IR node properties to make sure they match the expectations. Finally, generate Fortran code with `fgen` and check that the output is correct.

2) Ideally, we would implement this also for the other frontends (OFP and OMNI), provided they support Forall. However, I'd be prepared to waive this requirement or take a quick look at it myself once we have tests.

Thanks again and please reach out if you have any questions about this!

**Comment by quepas** [comment]
@reuterbal I have added some unit test of the Forall statement/construct. I will try to work on the OFP/OMNI parsers soon as well :)

**Comment by reuterbal** [comment]
Apologies for the delay in getting back to this. I have fixed the tests and added (limited) support for Forall to the other frontends. OMNI seems to be doing entirely stupid things but OFP can at least parse two out of three test cases.

@quepas: Please have a look if this looks ok to you.

Thanks!

**Comment by quepas** [comment]
It looks great! Sorry for the lack of activity from my side on this pull request. I tried to program the FORALL for the OFP, but I failed initially :P

**Review by reuterbal — APPROVED** [review]

**Review by mlange05 — APPROVED** [review]
Ok, this looks fantastic! Many thanks to you both, @quepas and @reuterbal .

Regression tests are due to access restrictions for external contributors, so all GTG from me. :shipit:

**Pull request merged**
