### PR TITLE
CMake plan and enrichment bugfix

### PR DESCRIPTION
**Pull request by reuterbal**
This fixes two errors spotted with complex Fortran module dependencies:

1. When including module files in transformations, we had inconsistent behaviour between the files in a dependency graph that are going to be written, and those that are listed in the CMake plan. 74409002d6bd05e83504804806a92ae393e17186 applies the methodology that is used to derive the file graph for the `FileWriteTransformation` also when deriving the file list in the CMake plan writing, thus ensuring consistent behaviour.
2. For indirect imports, e.g., when importing a symbol from a module, where the symbol itself is only available because of an import from a third module, enrichment failed non-gracefully because we had the presumed origin module available but that module didn't have the symbol information available. e9a77f425bbc884fff26f0e3b3533c4c5edd60ed fixes the failure by not enriching the symbol, which is the correct approach if the information is not available. A corresponding test is supplied.

### CODE REVIEW

**Comment by reuterbal** [comment]
I added a test for the FileWriteTransformation/CMake planning - I had this but forgot to push it previously. This verifies the aligned behaviour between the two.

**Comment by reuterbal** [comment]
Thanks @awnawab for the pointer regarding the `replicate` property on items. This turned out to be indeed the issue that broke the ecwam regression test. I have now added a test that verifies this behaviour in Loki's testbase itself.

Similarly to the `is_ignored` property, we had to propagate this property upward to the `FileItem` to make sure this property is honoured when iterating over the file graph.

**Review by mlange05 — APPROVED** [review]
Yes, looks great. GTG from me. :shipit:

**Review by awnawab — APPROVED** [review]
Many thanks for this, removing this inconsistency will really help to clean up some of my config files 🙏 G2G 👌

**Pull request merged**
